dist: bionic

before_install:
- wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz 
- tar -zxvf cmake-3.20.0.tar.gz 
- cd cmake-3.20.0 
- ./bootstrap 
- make 
- make install
