dist: trusty
sudo: false
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate http://cmake.org/files/LatestRelease/cmake-3.20.0-linux-x86_64.tar.gz
  - tar -xvf cmake-3.20.0-linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.20.0-linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - mkdir build
  - cd build
  - cmake .. -DGMX_BUILD_OWN_FFTW=ON 

script:
  - make
  - make install
  - source /usr/local/gromacs/bin/GMXRC

