language: cpp
dist: bionic

# Update repositories and get the packages needed
before install:
- sudo apt-get update
- sudo apt-get install gcc 
- sudo apt-get install build-essential libssl-dev 

# Download and install CMAKE 
-sudo apt-get install cmake 
